### ISSUE TITLE
Can't import EpochRangeModifier

### ISSUE THREAD

**Issue by clementpoiret** [neuralmagic/sparsify#111]
**Describe the bug**
When trying to create a recipe, the recipe cannot be generated because sparseml.pytorch.optim.EpochRangeModifier cannot be imported. From what I understood, it's because modifier.py moved from optim to sparsification in sparseml.

**Expected behavior**
Generate a recipe :)

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]: Arch
2. Python version [e.g. 3.7]: 3.8
3. Sparsify version or commit hash [e.g. 0.1.0, `f7245c8`]: 0.12
4. ML framework version(s) [e.g. torch 1.7.1]: PyTorch 1.9.1
5. Other Python package versions [e.g. SparseZoo, DeepSparse, numpy, ONNX]:  sparseml 0.12
6. Other relevant environment information [e.g. hardware, CUDA version]: N/A

**To Reproduce**
Exact steps to reproduce the behavior:
* Import an onnx model (it sounds like the initial benchmark doesn't work either, I get "job cancelled".
* Create a recipe using sparsify.

**Errors**
If applicable, add a full print-out of any errors or exceptions that are raised or include screenshots to help explain your problem.
It simply says it cannot import EpochRangeModifier from sparseml

**Additional context**
Add any other context about the problem here. Also include any relevant files.

**Comment by markurtz** [comment]
Hi @clementpoiret, thanks for bringing this up it's tied to https://github.com/neuralmagic/sparseml/issues/670 as well. We're actively looking into it and hope to have a solution up soon!

**Comment by clementpoiret** [comment]
Oops you're right, it's the same issue, sorry for the duplicate :)

**Comment by markurtz** [comment]
No problem, we've landed this diff now on main and will be cutting out a hot fix release by early next week, will update here once that is available: https://github.com/neuralmagic/sparsify/pull/110
