### ISSUE TITLE
Transformers Text Classification Profiling fails and crases sparsify server (data indices for a Gather operation)

### ISSUE THREAD

**Issue by sullivancolin** [neuralmagic/sparsify#115]
**Describe the bug**
When trying to perform an initial profile of a transformers style text classification model an error is thrown relating to indices out of bounds for a Gather operation.  The profiling stops and the server crashes

**Expected behavior**
Completion of profiling for a valid onnx export of a huggingface text classification model.

**Environment**
Include all relevant environment information:
1. Debian- 11 - bullseye (Docker).  AWS C6i.8xlarge
2. Python 3.9.12
3. Sparsify '0.12.1'
4. torch: '1.9.1+cpu'
5.
- onnxruntime = "^1.11.1"
- sparsify = "^0.12.1"
- deepsparse = "^0.12.1"
- torch = {url = "https://download.pytorch.org/whl/cpu/torch-1.9.1%2Bcpu-cp39-cp39-linux_x86_64.whl"}
- onnx = "<=1.10.1"
- sparseml = "^0.12.1"
- transformers = {url = "https://github.com/neuralmagic/transformers/releases/download/nightly/transformers-4.18.0.dev0-py3-none-any.whl"}
- protobuf = "<=3.20"
- datasets = "^2.2.2"

6.  AWS C6i.8xlarge

**To Reproduce**
1.  Make a fresh 3 class text classifier based on distilbert
```python
from transformers import AutoTokenizer, AutoModelForSequenceClassification
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-multilingual-cased")
model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-multilingual-cased", num_labels=3)

model.save_pretrained("new_text_classifier")
tokenizer.save_pretrained("new_text_classifier")
```

2. Export from transformers to onnx
```sh
sparseml.transformers.export_onnx --model_path new_text_classifier/ --sequence_length 128 --task text-classification
```

3. Start sparisfy
```sh
sparsify --working-dir=.
```

4. Enter path to model to upload `new_text_classifier/model.onnx`
5. Hit `Run` to start profiling

**Errors**
```sh
2022-05-26 19:08:07.628652552 [E:onnxruntime:, sequential_executor.cc:352 Execute] Non-zero status code returned while running Gather node. Name:'Gather_7' Status Message: indices element out of data bounds, idx=5335349968635603386 must be within the inclusive range [-119547,119546]
NM: Fatal error encountered: Non-zero status code returned while running Gather node. Name:'Gather_7' Status Message: indices element out of data bounds, idx=5335349968635603386 must be within the inclusive range [-119547,119546], exiting.
```
![Screen Shot 2022-05-26 at 3 09 10 PM](https://user-images.githubusercontent.com/10760217/170559599-afbca81e-b89e-4f27-96aa-9593848af319.png)
![Screen Shot 2022-05-26 at 3 09 27 PM](https://user-images.githubusercontent.com/10760217/170559640-f26094b7-4b54-4441-8867-abb027181a7e.png)

**Additional context**
Add any other context about the problem here. Also include any relevant files.

**Comment by jeanniefinks** [comment]
Hello @sullivancolin 
The Neural Magic team has been busy working on the next generation of Sparsify which will have much-improved pathways for users to interact and get results. We are very excited to see that go live later this year. As such, we will be closing this ticket. 

We did want to invite users who are interested in being Sparsify testers and giving feedback to contact our UX lead Rob Fitzgibbon (@NMfitz). We would be happy to make it worth your time with a gift card if you do! 

Best and thank you, Jeannie / Neural Magic
