### ISSUE TITLE
Sparse-fication recipe for yolov7

### ISSUE THREAD

**Issue by sandyflute** [neuralmagic/sparsify#120]
Hello there,

Thanks for working in Sparsify. This speed-ups are very impressive and amazing. 

[Yolov7](https://github.com/WongKinYiu/yolov7) has been released recently and it is faster and more accurate than other object detectors at the moment. Do we have a plan to write sparse-fication recipe for this ?

I am open to work individually or with people to create a pull request.

**Comment by jeanniefinks** [comment]
Hi @sandyflute 
With the newer version of SParsify, YOLOv7 will be supported

In other news, the Neural Magic team has been busy working on the next generation of Sparsify which will have much-improved pathways for users to interact and get results. We are very excited to see that go live later this year. As such, we will be closing this ticket.

We did want to invite users who are interested in being Sparsify testers and giving feedback to contact our UX lead Rob Fitzgibbon (@NMfitz). We would be happy to make it worth your time with a gift card if you do!

Best and thank you, Jeannie / Neural Magic

**Comment by NMfitz** [comment]
Hi @sandyflute  - yes, as per @jeanniefinks, we're looking to do some user interviews; please let me know if that might be something that would interest you - Fitz
