### ISSUE TITLE
Browser freezes when performing optimization (Mac M1 Max)

### ISSUE THREAD

**Issue by cyprian** [neuralmagic/sparsify#137]
**Describe the bug**
After the performance of the model is analized, I am clicking on Optimize.
At this moment the page changes to "Optimization" and the browser freezes after 5 seconds.

**Expected behavior**
Optimization should start but does not. 

**Environment**
Include all relevant environment information:
1. OS Mac OS Monterey 12.6
2. Python version 3.10.4
3. Sparsify version or commit hash 1.0.0
4. ML framework version(s) pytorch 1.12.1
5. Other Python package versions [e.g. SparseZoo, DeepSparse, numpy, ONNX]: onnx 1.10.1, onnxruntime 1.12.1, sparsezoo 1.0.0, numpy 1.21.6 (note: DeepSparse not installed b/c of Mac m1 chip)
6. Other relevant environment information [e.g. hardware, CUDA version]: Apple M1 Max 64GB

**To Reproduce**
Exact steps to reproduce the behavior:

**Errors**
<img width="1186" alt="Screenshot 2022-09-28 at 10 47 41" src="https://user-images.githubusercontent.com/849865/192735655-7f916627-ba88-4fc8-abcc-1ba884fdac02.png">

**Additional context**
Add any other context about the problem here. Also include any relevant files.

**Comment by jeanniefinks** [comment]
Hi @cyprian 
The Neural Magic team has been busy working on the next generation of Sparsify which will have much-improved pathways for users to interact and get results. The UI will also change so the bug you encountered will not be able to reproducible. . We are very excited to see that go live later this year. As such, we will be closing this ticket.

We wanted to invite users who are interested in being Sparsify testers and giving feedback to contact our UX lead Rob Fitzgibbon (@NMfitz). We would be happy to make it worth your time with a gift card if you do!

Best and thank you, Jeannie / Neural Magic

**Comment by NMfitz** [comment]
Hi @cyprian  as @jeanniefinks said, we are doing some user research for the Sparsify product - please let me know if you'd be interested in being interviewed! - Fitz

**Comment by cyprian** [comment]
> Hi @cyprian as @jeanniefinks said, we are doing some user research for the Sparsify product - please let me know if you'd be interested in being interviewed! - Fitz

Hi @NMfitz yes I am happy to help. You can reach me on the sparsify Slack channel.
