### ISSUE TITLE
errored out Invalid input shape, cannot create a random input shape from: (3, None, None)

### ISSUE THREAD

**Issue by PasaOpasen** [neuralmagic/sparsify#169]
I have a model with dynamic input shape `[batches, 3, height, width]` (dynamic `height`, `width`), so sparsify raises errors on profiling. How can I provide input examples or something to solve this?

**Comment by jeanniefinks** [comment]
Hello @PasaOpasen 
Apologies for the response delay: dynamic input shape is not supported in Sparsify at this time. The easiest fix would be to export again with a static shape. If you're not able to, we'd need more information on either the export code or model architecture.

Thank you. Jeannie / Neural Magic

**Comment by jeanniefinks** [comment]
Hi @PasaOpasen 
Because some time has passed, and there are no further questions, I will close this issue now. Please re-open it if you have follow-up questions. Regards, Jeannie / Neural Magic
