### ISSUE TITLE
sparsifyml-nightly package no longer exists on neuralmagic pypi mirror

### ISSUE THREAD

**Issue by EricPedley** [neuralmagic/sparsify#297]
**Describe the bug**
When running `sparsify.login <my token>`, I get this error
```
INFO:sparsify.login:Logging into sparsify...
INFO:sparsify.utils.helpers:Successfully authenticated with Neural Magic Account API key
INFO:sparsify.login:Installing sparsifyml version 1.7 from neuralmagic pypi server
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://nm:****@pypi.neuralmagic.com
ERROR: Could not find a version that satisfies the requirement sparsifyml-nightly~=1.7 (from versions: none)
ERROR: No matching distribution found for sparsifyml-nightly~=1.7
``` 
I modified the source of `login.py` to run `pip index versions sparsifyml-nightly --index-url (index url with auth token)` and it outputs `ERROR: No matching distribution found for sparsifyml-nightly`.

**Expected behavior**
I expect `sparsify.login` to run without errors and successfully install `sparsifyml-nightly`.

**Environment**
1. OS [e.g. Ubuntu 18.04]: Ubuntu 22.04
2. Python version [e.g. 3.8]: 3.10
3. Sparsify version or commit hash [e.g. 0.1.0, `f7245c8`]: 1.7
4. ML framework version(s) [e.g. torch 1.7.1]: 2.1.2
5. Other Python package versions [e.g. SparseZoo, DeepSparse, numpy, ONNX]:
```
deepsparse-nightly==1.8.0.20240404
sparseml-nightly==1.7.0.20240131
sparsezoo-nightly==1.7.0.20240304
```
7. Other relevant environment information [e.g. hardware, CUDA version]:
Nvidia 3080, CUDA 12.4

**To Reproduce**
Exact steps to reproduce the behavior:
`sparsify.login <your token>`

**Comment by robertgshaw2-neuralmagic** [comment]
Hey @EricPedley, we are not actively developing sparsify anymore. Please check out our project llm-compressor (https://github.com/vllm-project/llm-compressor) if you want to try out our tools!

Thanks!
