### ISSUE TITLE
Error While exporting the model

### ISSUE THREAD

**Issue by NM0727** [neuralmagic/sparsify#77]
hello ,I followed all the steps in the document for my custom model of yolov5 and got struck near exporting step .could you please help me with it ?
![image](https://user-images.githubusercontent.com/87924373/126889178-640a3c57-c523-4a63-9a09-e26e45617543.png)

**Comment by bfineran** [comment]
Hi @NM0727 what version of PyTorch are you using?

**Comment by NM0727** [comment]
> Hi @NM0727 what version of PyTorch are you using?

1.0.0

**Comment by bfineran** [comment]
@NM0727 could you try updating your pytorch version to 1.6 or 1.7? 

It looks like sparsify is trying to import some newer pytorch modules. This should usually be caught, I'll look into the issue. In the meantime, upgrading pytorch may fix this.

**Comment by NM0727** [comment]
@bfineran Thank you. It worked with pytorch version 1.7
