### ISSUE TITLE
How to Implement config file in training pipeline

### ISSUE THREAD

**Issue by K-prog** [neuralmagic/sparsify#78]
I have optimized my model via sparsify and have got the config file but I don't know how to use the config file with the optimization code given:
![image](https://user-images.githubusercontent.com/52241581/126912229-abb60f85-b339-4ac3-87b7-38e0931df3a0.png)

I made a python file where I loaded my PyTorch model and passed it to the function 'ScheduledOptimizer' as the 'MODEL' parameter given in the above 'Code for optimization' but I don't know what is the optimizer variable or what to pass to it and if I leave it like this only it says 
"optimizer" is not defined.

**Comment by markurtz** [comment]
Hi @K-prog, thank you for trying out Sparsify and bringing up this issue! The "Code for optimization" is listed there as example code for integrating into your existing training pipeline. The optimizer variable would be your existing optimizer variable for whichever training script you are currently using to train the model. Ideally you should be able to plug in those few lines of code and it will work with any training pipeline. More info on integrating the recipes into training pipelines can be found in SparseML here: https://github.com/neuralmagic/sparseml

We're working on significant upgrades to Sparsify in the next few months, so we'll be sure to include some clearer documentation!

Until then, we're more than happy to help with integration currently. Is there a particular repository you're working on that we could instruct further on how to enable the recipes to run with it?

**Comment by jeanniefinks** [comment]
Hey there @K-prog 
Checking in here to see if there was a specific repo you were working with? Are you still interested in resolving this issue? Thank you for your insight.
Jeannie / Neural Magic

**Comment by jeanniefinks** [comment]
Hello @K-prog 
As there have been no further comments on this, we will close out this issue. Feel free to re-open it however if you would like to continue the conversation. 
Thank you! Jeannie / Neural Magic
