### ISSUE TITLE
Having a sparsify-cli component to interact with the deployed sparsify server

### ISSUE THREAD

**Issue by pacospace** [neuralmagic/sparsify#84]
**Is your feature request related to a problem? Please describe.**
As NeuralMagic User,

I would like to have a `sparsify-cli` component that I can use to interact with the deployed server for sparsify. This would allow me to automate the sparsify step to obtain a recipe (if it does not exists). In this way, the user does not need to use the UI but integrate that step in a pipeline that could retrieve an existing recipe if available and if not, it could request a recipe to the server providing the required inputs (e.g. URL to ONNX model).

**Describe the solution you'd like**
- Have a sparsify-cli component that can interact with the server.

**Describe alternatives you've considered**

**Additional context**

**Additional context**
See: https://github.com/AICoE/elyra-aidevsecops-tutorial/issues/297

**Comment by markurtz** [comment]
Thanks for the suggestion @pacospace, this is actually currently something we're working on! We're hoping to have an initial implementation for this in our 0.8 release in early October that will land in SparseML and Sparsify will use in the future. I'll keep this updated as those changes progress and land to see if you'd like to test them out.

Thanks,
Mark

**Comment by markurtz** [comment]
Hi @pacospace, a CLI went out in SparseML with our 0.9 release! The following code can be used to replicate the Sparsify base functionality:

```
from sparseml.sparsification import create_pruning_recipe

ONNX_FILE_PATH = "/PATH/TO/MODEL.onnx"
create_pruning_recipe(ONNX_FILE_PATH)
```
